name: "PR:: Check"

on:
  pull_request:
    branches: ["**"]
    types: [opened, reopened, ready_for_review, synchronize]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Maven and Java
        uses: s4u/setup-maven-action@v1.16.0
        with:
          java-version: 17
          maven-version: 3.9.6

      - name: Build apps-maven-builder
        shell: bash
        run: |
          settings_xml=$(realpath .github/supporting_files/pr_check_settings.xml)
          export MAVEN_OPTIONS="-s ${settings_xml}"
          cd apps-maven-builder
          mvn clean install